{{- if .Values.amfs.apiKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "amfs.fullname" . }}-auth
  labels:
    {{- include "amfs.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-keys: {{ .Values.amfs.apiKeys | quote }}
{{- end }}
---
{{- if and (eq .Values.storage.backend "postgres") .Values.postgres.external .Values.postgres.dsn }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "amfs.fullname" . }}-db
  labels:
    {{- include "amfs.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ .Values.postgres.dsn | quote }}
{{- end }}
