"""AMFS Core — models, engine, and adapter ABC."""

from amfs_core.abc import AdapterABC, WatchHandle
from amfs_core.embedder import EmbedderABC, cosine_similarity
from amfs_core.engine import CausalTagger, CoWEngine, ReadTracker
from amfs_core.exceptions import (
    AMFSError,
    AdapterError,
    EntryNotFoundError,
    LockTimeoutError,
    StaleWriteError,
    VersionConflictError,
)
from amfs_core.lifecycle import LifecycleManager
from amfs_core.models import (
    AMFSConfig,
    Agent,
    Branch,
    BranchAccess,
    BranchAccessPermission,
    BranchStatus,
    ConfidenceChange,
    ConflictPolicy,
    ConsolidationProposal,
    ConsolidationReport,
    DecisionTrace,
    DiffEntry,
    Digest,
    DigestType,
    ErrorEvent,
    Event,
    EventType,
    ExternalContext,
    GraphEdge,
    GraphNeighborQuery,
    LayerConfig,
    MemoryEntry,
    MemoryStateDiff,
    MemoryStats,
    MergeConflict,
    MergeResult,
    MergeStrategy,
    PRReview,
    PRReviewStatus,
    PullRequest,
    PullRequestStatus,
    OutcomeRecord,
    OutcomeType,
    Provenance,
    QualityIssue,
    QualityReport,
    QueryEvent,
    SearchQuery,
    SemanticQuery,
    Tag,
    TraceEntry,
)
from amfs_core.outcome import OutcomeBackPropagator
from amfs_core.quality import (
    HeuristicQualityEvaluator,
    MemoryQualityEvaluator,
    NoOpQualityEvaluator,
)

__all__ = [
    "AMFSConfig",
    "AMFSError",
    "AdapterABC",
    "AdapterError",
    "Agent",
    "Branch",
    "BranchAccess",
    "BranchAccessPermission",
    "BranchStatus",
    "CausalTagger",
    "ConfidenceChange",
    "ConflictPolicy",
    "ConsolidationProposal",
    "ConsolidationReport",
    "CoWEngine",
    "DecisionTrace",
    "DiffEntry",
    "Digest",
    "DigestType",
    "EmbedderABC",
    "EntryNotFoundError",
    "ErrorEvent",
    "Event",
    "EventType",
    "ExternalContext",
    "GraphEdge",
    "GraphNeighborQuery",
    "LayerConfig",
    "LifecycleManager",
    "LockTimeoutError",
    "MemoryEntry",
    "MemoryStateDiff",
    "MemoryStats",
    "MergeConflict",
    "MergeResult",
    "MergeStrategy",
    "PRReview",
    "PRReviewStatus",
    "PullRequest",
    "PullRequestStatus",
    "HeuristicQualityEvaluator",
    "MemoryQualityEvaluator",
    "NoOpQualityEvaluator",
    "OutcomeBackPropagator",
    "OutcomeRecord",
    "OutcomeType",
    "Provenance",
    "QualityIssue",
    "QualityReport",
    "QueryEvent",
    "ReadTracker",
    "SearchQuery",
    "SemanticQuery",
    "StaleWriteError",
    "Tag",
    "TraceEntry",
    "VersionConflictError",
    "WatchHandle",
    "cosine_similarity",
]
